export const JOB_ROLE_SUGGESTIONS = [
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Software Engineer",
  "DevOps Engineer",
  "Cloud Engineer",
  "Mobile App Developer",
  "Android Developer",
  "iOS Developer",
  "UI/UX Designer",
  "Product Designer",
  "QA Engineer",
  "Cybersecurity Analyst",
  "Data Analyst",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI Engineer",
  "Business Analyst",
  "Product Manager",
  "Project Coordinator",
  "Sales Executive",
  "Business Development Executive",
  "Digital Marketing Executive",
  "Content Strategist",
  "HR Associate",
  "Finance Analyst",
  "Operations Analyst",
  "Supply Chain Analyst",
  "Customer Success Associate",
  "Technical Support Engineer",
  "Mechanical Engineer",
  "Design Engineer - Mechanical",
  "Production Engineer",
  "Civil Engineer",
  "Site Engineer",
  "Structural Engineer",
  "Electrical Engineer",
  "Power Systems Engineer",
  "Electronics Engineer",
  "ECE Engineer",
  "Embedded Systems Engineer",
  "VLSI Design Engineer",
  "Instrumentation Engineer",
  "Automobile Engineer",
  "Robotics Engineer",
  "Industrial Engineer",
  "Biomedical Engineer",
  "Chemical Engineer",
  "Environmental Engineer",
  "Logistics Coordinator",
];

export const TECH_STACK_SUGGESTIONS = {
  "Full Stack Developer": "React, Node.js, Express, MongoDB, TypeScript, REST APIs",
  "Frontend Developer": "React, Next.js, TypeScript, Tailwind CSS, Accessibility, Responsive UI",
  "Backend Developer": "Node.js, Express, PostgreSQL, Redis, REST APIs, Authentication",
  "Software Engineer": "DSA, OOP, System Design, Java or Python, SQL, Problem Solving",
  "DevOps Engineer": "Docker, Kubernetes, Jenkins, AWS, Terraform, CI/CD",
  "Cloud Engineer": "AWS or Azure or GCP, Terraform, IAM, Networking, Monitoring",
  "Mobile App Developer": "React Native or Flutter, APIs, State Management, Mobile Performance",
  "Android Developer": "Kotlin, Android SDK, Jetpack, MVVM, Firebase",
  "iOS Developer": "Swift, SwiftUI, UIKit, Core Data, REST APIs",
  "UI/UX Designer": "Figma, User Research, Wireframing, Prototyping, Design Systems",
  "Product Designer": "Figma, UX Strategy, Interaction Design, Design Systems, Usability Testing",
  "QA Engineer": "Manual Testing, Automation Testing, Selenium, API Testing, Test Cases",
  "Cybersecurity Analyst": "Network Security, SIEM, Vulnerability Assessment, Incident Response, SOC",
  "Data Analyst": "Excel, SQL, Power BI, Tableau, Python, Data Cleaning",
  "Data Scientist": "Python, Pandas, NumPy, scikit-learn, Statistics, Visualization",
  "Machine Learning Engineer": "Python, TensorFlow, PyTorch, Model Deployment, Feature Engineering",
  "AI Engineer": "LLMs, Python, Prompt Engineering, RAG, Vector Databases, APIs",
  "Business Analyst": "Requirement Gathering, BRD, FRD, SQL, Excel, Power BI, Stakeholder Management",
  "Product Manager": "Product Strategy, Roadmaps, User Stories, Metrics, Prioritization, GTM",
  "Project Coordinator": "Project Planning, Documentation, Jira, Scheduling, Communication",
  "Sales Executive": "Lead Generation, CRM, Objection Handling, Negotiation, Pipeline Management",
  "Business Development Executive": "Prospecting, Partnerships, Client Outreach, CRM, Pitching",
  "Digital Marketing Executive": "SEO, SEM, Google Analytics, Meta Ads, Content Marketing, Campaigns",
  "Content Strategist": "Content Planning, SEO Writing, Editorial Calendar, Brand Messaging",
  "HR Associate": "Recruitment, Screening, Onboarding, HR Operations, Employee Engagement",
  "Finance Analyst": "Excel, Financial Modeling, Budgeting, Forecasting, Ratio Analysis",
  "Operations Analyst": "Process Improvement, Excel, Reporting, KPI Tracking, Stakeholder Coordination",
  "Supply Chain Analyst": "Inventory Management, Procurement, Forecasting, ERP, Logistics",
  "Customer Success Associate": "Client Communication, CRM, Retention, Issue Resolution, Onboarding",
  "Technical Support Engineer": "Troubleshooting, APIs, Logs, Networking Basics, Customer Support",
  "Mechanical Engineer": "CAD, SolidWorks, Manufacturing Processes, Thermodynamics, GD&T",
  "Design Engineer - Mechanical": "CAD, SolidWorks, AutoCAD, Design Calculations, Materials",
  "Production Engineer": "Lean Manufacturing, Process Optimization, Quality Control, Production Planning",
  "Civil Engineer": "AutoCAD, RCC, Surveying, Site Execution, Estimation",
  "Site Engineer": "Construction Supervision, BOQ, AutoCAD, Site Planning, Quality Checks",
  "Structural Engineer": "STAAD Pro, ETABS, RCC Design, Load Calculations, Structural Analysis",
  "Electrical Engineer": "Power Systems, Circuit Design, Electrical Machines, Protection Systems",
  "Power Systems Engineer": "Load Flow, Protection, Substations, Grid Operations, MATLAB",
  "Electronics Engineer": "Analog Circuits, Digital Electronics, PCB Basics, Embedded Systems",
  "ECE Engineer": "Communication Systems, Signal Processing, Embedded C, VLSI Basics, Electronics",
  "Embedded Systems Engineer": "Embedded C, Microcontrollers, RTOS, UART, SPI, I2C",
  "VLSI Design Engineer": "Verilog, SystemVerilog, Digital Design, Timing Analysis, ASIC Flow",
  "Instrumentation Engineer": "PLC, SCADA, Sensors, Process Control, Calibration",
  "Automobile Engineer": "Automotive Systems, CAD, Vehicle Dynamics, Manufacturing, Testing",
  "Robotics Engineer": "ROS, Python, Control Systems, Sensors, Actuators, Embedded Systems",
  "Industrial Engineer": "Process Improvement, Lean, Six Sigma, Operations, Production Planning",
  "Biomedical Engineer": "Medical Devices, Signal Processing, Embedded Systems, Regulatory Basics",
  "Chemical Engineer": "Process Design, Mass Transfer, Heat Transfer, Plant Operations, Safety",
  "Environmental Engineer": "Wastewater Treatment, Sustainability, EIA, Environmental Compliance",
  "Logistics Coordinator": "Shipment Planning, Vendor Coordination, Inventory Tracking, ERP, Reporting",
};
